name : testProject
on : push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: getCode
        uses: actions/checkout@v3
      - name: Install Node jobs
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: run test
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          version: 18
      - name: install dependencies
        run : npm ci
      - name: building
        run : npm run build
      - name : deploy
        run : echo " deploying ......"
        
